services:
  - type: web
    name: langflow
    env: python
    plan: free  # or 'starter' if you're using paid plan
    buildCommand: pip install -r requirements.txt
    startCommand: langflow run
    envVars:
      - key: LANGFLOW_ENV
        value: production
      - key: PORT
        value: 10000
