services:
  - type: web
    name: langflow
    env: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry install
    startCommand: poetry run langflow run --host 0.0.0.0 --port $PORT
      - key: LANGFLOW_ENV
        value: production
      - key: PORT
        value: 10000
